### ISSUE TITLE
Missing ./lib/ folder

### ISSUE THREAD

**Issue by ruyadorno** [jonschlinkert/lookup-deps#2]
I installed it on a project to give it a try but I'm getting the following error:

``` js
module.js:340
    throw err;
    ^
Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/ruy.adorno/Documents/workspace/generator-html5/node_modules/lookup-deps/index.js:19:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Weird thing is that when I open the installed folder on `./node_modules/lookup_deps/` I can't really find the `./lib/` folder there. 

Can it be a problem with the npm published version?

Thanks in advance,

**Comment by jonschlinkert** [comment]
wow I am so sorry, I didn't notice this issue before. You probably moved on after this, but if you do in fact still have the issue I'd be happy to get it fixed.

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
